import { lazy } from 'react'
import type { BlogMeta } from '../BlogLayout'

// Blog posts registry — newest first
export const BLOG_POSTS: BlogMeta[] = [
  {
    slug: 'expose-verstehen',
    title: 'Exposé verstehen: So lesen Käufer Immobilienangaben richtig',
    description: 'Pflichtangaben vs. Werbung, Wohnfläche-Fallen, Maklersprache decoded — wie Sie jedes Exposé in 5 Minuten richtig einordnen.',
    date: '11. April 2026',
    readTime: '13 Min',
    tags: ['Kaufratgeber'],
  },
  {
    slug: 'besichtigung-vorbereitung',
    title: 'Besichtigungs-Vorbereitung: Welche Fragen Käufer vor Ort unbedingt stellen sollten',
    description: '30+ konkrete Fragen für die Immobilienbesichtigung — sortiert nach 8 Themenbereichen, mit Erklärung warum jede Frage wichtig ist.',
    date: '11. April 2026',
    readTime: '13 Min',
    tags: ['Checkliste', 'Kaufratgeber'],
  },
  {
    slug: 'zustand-folgekosten',
    title: 'Zustand und Folgekosten: Warum günstige Immobilien oft teurer werden als gedacht',
    description: 'Die Rechnung die viele Käufer nicht machen: Warum eine 220.000-€-Wohnung über 20 Jahre genauso viel kostet wie eine für 295.000 €.',
    date: '11. April 2026',
    readTime: '12 Min',
    tags: ['Kaufratgeber', 'Finanzierung'],
  },
  {
    slug: 'baujahr-einordnen',
    title: 'Baujahr richtig einordnen: Was Käufer daraus wirklich ableiten können',
    description: 'Von Gründerzeit bis GEG-Neubau: Was jede Bauepoche über Bauweise, Energie, Schadstoffe und Sanierungsbedarf verrät.',
    date: '11. April 2026',
    readTime: '14 Min',
    tags: ['Kaufratgeber'],
  },
  {
    slug: 'immobilien-check-vor-kauf',
    title: 'Immobilien-Check vor dem Kauf: So erkennen Käufer Risiken frühzeitig',
    description: '7 Prüfbereiche, 30-Minuten Schnell-Check und Ampelsystem — wie Sie Risiken erkennen bevor sie zu Kosten werden.',
    date: '11. April 2026',
    readTime: '12 Min',
    tags: ['Checkliste', 'Kaufratgeber'],
  },
  {
    slug: 'fehler-immobilienkauf',
    title: 'Fehler beim Immobilienkauf: Diese teuren Irrtümer passieren besonders häufig',
    description: '10 häufige Fehler beim Hauskauf — von unterschätzten Nebenkosten bis zum ignorierten Energieausweis. Mit konkreten Folgekosten und Vermeidungsstrategien.',
    date: '11. April 2026',
    readTime: '13 Min',
    tags: ['Kaufratgeber'],
  },
  {
    slug: 'hauskauf-mit-system',
    title: 'Hauskauf mit System: So treffen Käufer fundiertere Entscheidungen',
    description: 'Der 5-Phasen-Kaufprozess: Anforderungen, Exposé-Vorprüfung, Besichtigung mit Checkliste, Bewertung, Verhandlung — Schritt für Schritt erklärt.',
    date: '11. April 2026',
    readTime: '13 Min',
    tags: ['Checkliste', 'Kaufratgeber'],
  },
  {
    slug: 'immobilienbewertung-kaeufer',
    title: 'Immobilienbewertung für Käufer: Welche Faktoren wirklich über den Wert entscheiden',
    description: 'Lage, Zustand, Energie, Baujahr, Grundriss — die 10 Faktoren die den Immobilienwert bestimmen und wie Profis bewerten.',
    date: '11. April 2026',
    readTime: '13 Min',
    tags: ['Kaufratgeber'],
  },
  {
    slug: 'angebotspreis-fair',
    title: 'Angebotspreis fair? So prüfen Käufer, ob der Immobilienpreis plausibel ist',
    description: '3 Methoden zur Preiseinordnung, 8 Faktoren die den fairen Preis bestimmen und ein Praxisbeispiel mit konkreter Berechnung.',
    date: '11. April 2026',
    readTime: '12 Min',
    tags: ['Kaufratgeber'],
  },
  {
    slug: 'expose-analyse-vor-besichtigung',
    title: 'Exposé-Analyse vor der Besichtigung: So filtern Käufer Angebote effizienter',
    description: 'Das 3-Stufen-Filtersystem: Grundcheck, Kennzahlen, Kontext-Recherche — so sparen Sie dutzende Stunden Fehlbesichtigungen.',
    date: '11. April 2026',
    readTime: '12 Min',
    tags: ['Checkliste', 'Kaufratgeber'],
  },
  {
    slug: 'was-im-expose-fehlt',
    title: 'Was im Exposé oft fehlt: Welche Angaben Käufer aktiv einfordern sollten',
    description: 'Sanierungshistorie, Heizungsalter, WEG-Protokolle, Baulasten — 10 Angaben die in Exposés fehlen und warum Sie sie brauchen.',
    date: '11. April 2026',
    readTime: '12 Min',
    tags: ['Kaufratgeber'],
  },
  {
    slug: 'exposes-richtig-lesen',
    title: 'Immobilienkauf für Einsteiger: Wie Sie Exposés richtig lesen',
    description: 'Quadratmeterpreis, Baujahr, Energieklasse, Hausgeld — die 5 wichtigsten Zahlen und was Einsteiger häufig über- oder unterschätzen.',
    date: '11. April 2026',
    readTime: '12 Min',
    tags: ['Kaufratgeber'],
  },
  {
    slug: 'hauskauf-vorbereiten',
    title: 'Hauskauf vorbereiten: Welche Daten Sie vor der Besichtigung prüfen sollten',
    description: 'Exposé auswerten, Lage recherchieren, Finanzen durchrechnen — die 60-Minuten-Vorprüfung die Ihnen teure Fehlbesichtigungen erspart.',
    date: '11. April 2026',
    readTime: '11 Min',
    tags: ['Checkliste', 'Kaufratgeber'],
  },
  {
    slug: 'immobilien-vergleichen',
    title: 'Immobilien vergleichen: Welche Kennzahlen wirklich aussagekräftig sind',
    description: 'Kaufpreis, Quadratmeterpreis, Energieklasse — welche 8 Kennzahlen einen echten Vergleich ermöglichen und welche Fehler Sie vermeiden sollten.',
    date: '11. April 2026',
    readTime: '11 Min',
    tags: ['Kaufratgeber'],
  },
  {
    slug: 'sanierungsbedarf-erkennen',
    title: 'Sanierungsbedarf erkennen: Erste Hinweise schon im Exposé',
    description: 'Baujahr, Energieklasse, fehlende Sanierungsangaben — welche Exposé-Signale auf versteckte Kosten hindeuten und was Sanierung wirklich kostet.',
    date: '11. April 2026',
    readTime: '12 Min',
    tags: ['Kaufratgeber'],
  },
  {
    slug: 'lagebewertung-hauskauf',
    title: 'Lagebewertung beim Hauskauf: Warum die Adresse allein nicht reicht',
    description: 'Makrolage, Mikrolage, Lärmkarten, Hochwasserrisiko — welche 8 Lagefaktoren den Immobilienwert wirklich bestimmen und wie Sie sie prüfen.',
    date: '11. April 2026',
    readTime: '11 Min',
    tags: ['Standort', 'Kaufratgeber'],
  },
  {
    slug: 'kaufnebenkosten-immobilienkauf',
    title: 'Kaufnebenkosten beim Immobilienkauf: Was Käufer oft unterschätzen',
    description: 'Grunderwerbsteuer, Notar, Makler — und dann noch Sanierung, Umzug und Sonderumlagen. So berechnen Sie die wahren Kosten eines Immobilienkaufs.',
    date: '11. April 2026',
    readTime: '10 Min',
    tags: ['Finanzierung', 'Kaufratgeber'],
  },
  {
    slug: 'energieausweis-expose',
    title: 'Energieausweis im Exposé: Was die Werte über eine Immobilie verraten',
    description: 'Verbrauchsausweis vs. Bedarfsausweis, Effizienzklassen A+ bis H, Heizkosten berechnen und typische Missverständnisse — so bewerten Sie Energiekennwerte richtig.',
    date: '11. April 2026',
    readTime: '11 Min',
    tags: ['Energie', 'Kaufratgeber'],
  },
  {
    slug: 'warnsignale-expose',
    title: 'Warnsignale im Immobilien-Exposé: Diese Punkte sollten Sie ernst nehmen',
    description: 'Fehlende Daten, Maklerfloskeln, unrealistische Preise — welche Warnsignale sofort misstrauisch machen und welche erst im Zusammenspiel kritisch werden.',
    date: '11. April 2026',
    readTime: '10 Min',
    tags: ['Kaufratgeber'],
  },
  {
    slug: 'quadratmeterpreis-bewerten',
    title: 'Quadratmeterpreis bewerten: Wann eine Immobilie zu teuer ist',
    description: 'Warum Vergleichswerte allein irreführend sind und welche 7 Faktoren den fairen Quadratmeterpreis bestimmen.',
    date: '11. April 2026',
    readTime: '9 Min',
    tags: ['Kaufratgeber'],
  },
  {
    slug: 'expose-pruefen',
    title: 'Immobilien-Exposé prüfen: Worauf Käufer wirklich achten sollten',
    description: 'Systematisch Exposés auswerten: Kennzahlen, Maklersprache, Red Flags und die Fragen, die Sie vor der Besichtigung stellen müssen.',
    date: '11. April 2026',
    readTime: '10 Min',
    tags: ['Kaufratgeber'],
  },
  {
    slug: 'hauskauf-checkliste-2026',
    title: 'Hauskauf-Checkliste 2026: Was Sie vor dem Kauf prüfen müssen',
    description: 'Die vollständige Checkliste für Ihren Immobilienkauf — von der Besichtigung bis zum Notar.',
    date: '11. April 2026',
    readTime: '8 Min',
    tags: ['Checkliste', 'Kaufratgeber'],
  },
  {
    slug: 'kaufnebenkosten-berechnen',
    title: 'Kaufnebenkosten berechnen: So viel kostet der Hauskauf wirklich',
    description: 'Grunderwerbsteuer, Notar, Makler — alle versteckten Kosten beim Immobilienkauf auf einen Blick.',
    date: '10. April 2026',
    readTime: '6 Min',
    tags: ['Finanzierung'],
  },
  {
    slug: 'energieausweis-verstehen',
    title: 'Energieausweis lesen und verstehen: Was die Klassen A bis H bedeuten',
    description: 'Was verrät der Energieausweis über Ihre Wunschimmobilie? Heizkosten, Sanierungsbedarf und Fördermittel erklärt.',
    date: '9. April 2026',
    readTime: '7 Min',
    tags: ['Energie'],
  },
  {
    slug: 'immobilie-richtig-bewerten',
    title: 'Immobilie bewerten: 3 Verfahren die Gutachter nutzen',
    description: 'Vergleichswert, Sachwert, Ertragswert — so ermitteln Profis den wahren Wert einer Immobilie.',
    date: '8. April 2026',
    readTime: '9 Min',
    tags: ['Kaufratgeber'],
  },
  {
    slug: 'standortanalyse-immobilien',
    title: 'Standortanalyse für Immobilien: Diese 8 Faktoren entscheiden',
    description: 'ÖPNV, Schulen, Lärm, Demografie — welche Standortfaktoren den Immobilienwert wirklich beeinflussen.',
    date: '7. April 2026',
    readTime: '7 Min',
    tags: ['Standort'],
  },
  {
    slug: 'makler-anschreiben-tipps',
    title: 'Makler anschreiben: So fallen Sie positiv auf',
    description: 'Das perfekte Anschreiben an den Makler — mit Mustervorlage und den 10 Fragen die Sie stellen sollten.',
    date: '6. April 2026',
    readTime: '5 Min',
    tags: ['Kaufratgeber'],
  },
]

// Map slug → lazy component (filled as posts are written)
export const POST_COMPONENTS: Record<string, React.LazyExoticComponent<React.ComponentType>> = {
  'expose-pruefen': lazy(() => import('./expose-pruefen')),
  'quadratmeterpreis-bewerten': lazy(() => import('./quadratmeterpreis-bewerten')),
  'warnsignale-expose': lazy(() => import('./warnsignale-expose')),
  'energieausweis-expose': lazy(() => import('./energieausweis-expose')),
  'kaufnebenkosten-immobilienkauf': lazy(() => import('./kaufnebenkosten-immobilienkauf')),
  'lagebewertung-hauskauf': lazy(() => import('./lagebewertung-hauskauf')),
  'sanierungsbedarf-erkennen': lazy(() => import('./sanierungsbedarf-erkennen')),
  'immobilien-vergleichen': lazy(() => import('./immobilien-vergleichen')),
  'hauskauf-vorbereiten': lazy(() => import('./hauskauf-vorbereiten')),
  'exposes-richtig-lesen': lazy(() => import('./exposes-richtig-lesen')),
  'was-im-expose-fehlt': lazy(() => import('./was-im-expose-fehlt')),
  'expose-analyse-vor-besichtigung': lazy(() => import('./expose-analyse-vor-besichtigung')),
  'angebotspreis-fair': lazy(() => import('./angebotspreis-fair')),
  'immobilienbewertung-kaeufer': lazy(() => import('./immobilienbewertung-kaeufer')),
  'hauskauf-mit-system': lazy(() => import('./hauskauf-mit-system')),
  'fehler-immobilienkauf': lazy(() => import('./fehler-immobilienkauf')),
  'immobilien-check-vor-kauf': lazy(() => import('./immobilien-check-vor-kauf')),
  'baujahr-einordnen': lazy(() => import('./baujahr-einordnen')),
  'zustand-folgekosten': lazy(() => import('./zustand-folgekosten')),
  'besichtigung-vorbereitung': lazy(() => import('./besichtigung-vorbereitung')),
  'expose-verstehen': lazy(() => import('./expose-verstehen')),
}
