import { lazy } from 'react'
import type { BlogMeta } from '../BlogLayout'

// Blog posts registry — newest first
export const BLOG_POSTS: BlogMeta[] = [
  {
    slug: 'rauchen-dampfen-wohnqualitaet',
    title: 'Rauchen, Dampfen und Wohnqualität: Welche Spuren Innenraumnutzung in Immobilien hinterlassen kann',
    description: 'Gerüche, Verfärbungen, Oberflächenspuren — wie sich Nutzungsgeschichte bei Besichtigungen erkennen lässt und was Sanierung kostet.',
    date: '19. April 2026',
    readTime: '13 Min',
    tags: ['Kaufratgeber', 'Besichtigung'],
    image: 'https://images.unsplash.com/photo-1522444195799-478538b28823?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'fristen-immobilienkauf',
    title: 'Wichtige Unterlagen und Fristen beim Immobilienkauf: Was Käufer rechtzeitig im Blick haben sollten',
    description: 'Die 12 wichtigsten Fristen im Kaufprozess chronologisch, Unterlagen-Matrix in drei Blöcken und ein praktikables Fristen-System für Privatkäufer.',
    date: '19. April 2026',
    readTime: '14 Min',
    tags: ['Kaufratgeber', 'Checkliste'],
    image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'immobilienanfragen-bearbeiten',
    title: 'Immobilienanfragen effizient bearbeiten: Wie Makler und Verkäufer Anfragen besser vorsortieren',
    description: 'Anfrageflut strukturiert bewältigen: Ampel-Raster, 5-Schritte-Prozess, sinnvolle Automatisierung und was Käufer daraus lernen können.',
    date: '19. April 2026',
    readTime: '13 Min',
    tags: ['Kaufratgeber', 'Checkliste'],
    image: 'https://images.unsplash.com/photo-1551836022-deb4988cc6c0?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'unterlagen-vor-immobilienkauf',
    title: 'Vor dem Immobilienkauf Unterlagen prüfen: Welche Dokumente wirklich wichtig sind',
    description: '12 Pflicht-Dokumente mit Timeline (vor Besichtigung → vor Kaufentscheidung → vor Notar), getrennt nach ETW und EFH.',
    date: '11. April 2026',
    readTime: '13 Min',
    tags: ['Checkliste', 'Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1560440021-33f9b867899d?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'immobilienkauf-mit-familie',
    title: 'Immobilienkauf mit Familie: Welche Kriterien besonders wichtig werden',
    description: 'Zimmeranzahl-Formel, familientauglicher Grundriss, Schulnähe, Garten, Sicherheit — 10 Familien-Kriterien mit Checkliste.',
    date: '11. April 2026',
    readTime: '14 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'infrastruktur-pruefen',
    title: 'Infrastruktur rund um die Immobilie prüfen: Was im Alltag wirklich zählt',
    description: 'Supermarkt, ÖPNV, Schule, Arzt, Internet — 8 Infrastruktur-Bereiche mit Richtwerten, Zielgruppen-Matrix und 15-Minuten Schnell-Check.',
    date: '11. April 2026',
    readTime: '13 Min',
    tags: ['Standort', 'Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1464082354059-27db6ce50048?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'nebenkosten-laufende-kosten',
    title: 'Nebenkosten und laufende Kosten unterscheiden: Was Käufer dauerhaft belastet',
    description: 'Einmalige Kaufnebenkosten vs. dauerhafte laufende Kosten — mit ETW- und EFH-Kostenaufstellung, 20-Jahres-Rechnung und Tragbarkeits-Faustregel.',
    date: '11. April 2026',
    readTime: '14 Min',
    tags: ['Finanzierung', 'Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'bilder-im-expose-bewerten',
    title: 'Bilder im Immobilien-Exposé richtig bewerten: Was Fotos zeigen – und was nicht',
    description: 'Weitwinkel, HDR, Home Staging — wie Exposé-Fotos entstehen, welche Details sie verraten und welche blinden Flecken sie haben.',
    date: '11. April 2026',
    readTime: '13 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'hausgeld-ruecklagen-sonderumlage',
    title: 'Hausgeld, Rücklagen, Sonderumlage: Was Wohnungskäufer wissen sollten',
    description: 'Hausgeld-Aufschlüsselung, Rücklage-Richtwerte, Sonderumlage-Kosten pro Einheit und 3 WEG-Szenarien — der komplette ETW-Kosten-Guide.',
    date: '11. April 2026',
    readTime: '14 Min',
    tags: ['Finanzierung', 'Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'wohnflaeche-richtig-einordnen',
    title: 'Wohnfläche richtig einordnen: Warum Quadratmeter allein nicht reichen',
    description: 'WoFlV vs. DIN 277, Dachschrägen-Illusion, Verkehrsflächen, Balkon-Anrechnung — warum 90 m² nicht gleich 90 m² sind.',
    date: '11. April 2026',
    readTime: '13 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1619468129361-605ebea04b44?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'grundriss-richtig-lesen',
    title: 'Grundriss im Exposé richtig lesen: Worauf Käufer achten sollten',
    description: 'Verkehrsflächen, Durchgangszimmer, Möblierbarkeit, Raumproportionen — 8 Prüfpunkte für jeden Grundriss plus Checkliste.',
    date: '11. April 2026',
    readTime: '13 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1619468129361-605ebea04b44?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'baujahr-und-modernisierung',
    title: 'Baujahr und Modernisierung: Wie Käufer beides zusammen bewerten sollten',
    description: 'Gleiches Baujahr, völlig verschiedene Häuser — warum nur die Kombination aus Baujahr und Sanierungshistorie eine realistische Bewertung ermöglicht.',
    date: '11. April 2026',
    readTime: '14 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'zustand-richtig-einschaetzen',
    title: 'Zustand einer Immobilie richtig einschätzen: Was Exposé und Besichtigung verraten',
    description: 'Zustandsbeschreibungen decoded, Foto-Analyse, Besichtigungs-Checkliste Raum für Raum und unsichtbare Mängel — der komplette Guide.',
    date: '11. April 2026',
    readTime: '14 Min',
    tags: ['Kaufratgeber', 'Checkliste'],
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'fehler-private-kaeufer',
    title: 'Private Käufer beim Hauskauf: Welche Fehler besonders häufig passieren',
    description: '10 typische Käuferfehler mit konkreten Folgekosten — von emotionaler Bindung über unterschätzte Nebenkosten bis zum Kauf unter Zeitdruck.',
    date: '11. April 2026',
    readTime: '14 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'einfamilienhaus-kaufen-expose',
    title: 'Einfamilienhaus kaufen: Worauf Käufer bei der Analyse achten sollten',
    description: 'Dach, Heizung, Keller, Grundstück, Erschließung — die EFH-spezifischen Prüfpunkte die über Traumhaus oder Kostenfalle entscheiden.',
    date: '11. April 2026',
    readTime: '14 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'eigentumswohnung-kaufen-expose',
    title: 'Eigentumswohnung kaufen: Welche Exposé-Angaben besonders wichtig sind',
    description: 'Hausgeld, Rücklage, WEG-Protokolle, Teilungserklärung — die ETW-spezifischen Daten die über Kauf oder Fehlkauf entscheiden.',
    date: '11. April 2026',
    readTime: '13 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'daten-statt-bauchgefuehl',
    title: 'Daten statt Bauchgefühl: Wie Käufer Immobilien fundierter bewerten',
    description: '10 Datenpunkte die jeder Käufer kennen muss, ein 30-Minuten Bewertungsprozess und warum Bauchgefühl ohne Fakten gefährlich ist.',
    date: '11. April 2026',
    readTime: '13 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1560440021-33f9b867899d?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'immobilien-realistischer-einordnen',
    title: 'Immobilien realistischer einordnen: Warum einzelne Kennzahlen oft täuschen',
    description: '5 Kennzahlen die isoliert irreführen, 3 gefährliche Denkfehler und wie Sie aus Einzelwerten eine belastbare Gesamteinschätzung ableiten.',
    date: '11. April 2026',
    readTime: '12 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'expose-verstehen',
    title: 'Exposé verstehen: So lesen Käufer Immobilienangaben richtig',
    description: 'Pflichtangaben vs. Werbung, Wohnfläche-Fallen, Maklersprache decoded — wie Sie jedes Exposé in 5 Minuten richtig einordnen.',
    date: '11. April 2026',
    readTime: '13 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1560440021-33f9b867899d?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'besichtigung-vorbereitung',
    title: 'Besichtigungs-Vorbereitung: Welche Fragen Käufer vor Ort unbedingt stellen sollten',
    description: '30+ konkrete Fragen für die Immobilienbesichtigung — sortiert nach 8 Themenbereichen, mit Erklärung warum jede Frage wichtig ist.',
    date: '11. April 2026',
    readTime: '13 Min',
    tags: ['Checkliste', 'Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'zustand-folgekosten',
    title: 'Zustand und Folgekosten: Warum günstige Immobilien oft teurer werden als gedacht',
    description: 'Die Rechnung die viele Käufer nicht machen: Warum eine 220.000-€-Wohnung über 20 Jahre genauso viel kostet wie eine für 295.000 €.',
    date: '11. April 2026',
    readTime: '12 Min',
    tags: ['Kaufratgeber', 'Finanzierung'],
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'baujahr-einordnen',
    title: 'Baujahr richtig einordnen: Was Käufer daraus wirklich ableiten können',
    description: 'Von Gründerzeit bis GEG-Neubau: Was jede Bauepoche über Bauweise, Energie, Schadstoffe und Sanierungsbedarf verrät.',
    date: '11. April 2026',
    readTime: '14 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'immobilien-check-vor-kauf',
    title: 'Immobilien-Check vor dem Kauf: So erkennen Käufer Risiken frühzeitig',
    description: '7 Prüfbereiche, 30-Minuten Schnell-Check und Ampelsystem — wie Sie Risiken erkennen bevor sie zu Kosten werden.',
    date: '11. April 2026',
    readTime: '12 Min',
    tags: ['Checkliste', 'Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1560440021-33f9b867899d?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'fehler-immobilienkauf',
    title: 'Fehler beim Immobilienkauf: Diese teuren Irrtümer passieren besonders häufig',
    description: '10 häufige Fehler beim Hauskauf — von unterschätzten Nebenkosten bis zum ignorierten Energieausweis. Mit konkreten Folgekosten und Vermeidungsstrategien.',
    date: '11. April 2026',
    readTime: '13 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'hauskauf-mit-system',
    title: 'Hauskauf mit System: So treffen Käufer fundiertere Entscheidungen',
    description: 'Der 5-Phasen-Kaufprozess: Anforderungen, Exposé-Vorprüfung, Besichtigung mit Checkliste, Bewertung, Verhandlung — Schritt für Schritt erklärt.',
    date: '11. April 2026',
    readTime: '13 Min',
    tags: ['Checkliste', 'Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'immobilienbewertung-kaeufer',
    title: 'Immobilienbewertung für Käufer: Welche Faktoren wirklich über den Wert entscheiden',
    description: 'Lage, Zustand, Energie, Baujahr, Grundriss — die 10 Faktoren die den Immobilienwert bestimmen und wie Profis bewerten.',
    date: '11. April 2026',
    readTime: '13 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'angebotspreis-fair',
    title: 'Angebotspreis fair? So prüfen Käufer, ob der Immobilienpreis plausibel ist',
    description: '3 Methoden zur Preiseinordnung, 8 Faktoren die den fairen Preis bestimmen und ein Praxisbeispiel mit konkreter Berechnung.',
    date: '11. April 2026',
    readTime: '12 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'expose-analyse-vor-besichtigung',
    title: 'Exposé-Analyse vor der Besichtigung: So filtern Käufer Angebote effizienter',
    description: 'Das 3-Stufen-Filtersystem: Grundcheck, Kennzahlen, Kontext-Recherche — so sparen Sie dutzende Stunden Fehlbesichtigungen.',
    date: '11. April 2026',
    readTime: '12 Min',
    tags: ['Checkliste', 'Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1560440021-33f9b867899d?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'was-im-expose-fehlt',
    title: 'Was im Exposé oft fehlt: Welche Angaben Käufer aktiv einfordern sollten',
    description: 'Sanierungshistorie, Heizungsalter, WEG-Protokolle, Baulasten — 10 Angaben die in Exposés fehlen und warum Sie sie brauchen.',
    date: '11. April 2026',
    readTime: '12 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1560440021-33f9b867899d?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'exposes-richtig-lesen',
    title: 'Immobilienkauf für Einsteiger: Wie Sie Exposés richtig lesen',
    description: 'Quadratmeterpreis, Baujahr, Energieklasse, Hausgeld — die 5 wichtigsten Zahlen und was Einsteiger häufig über- oder unterschätzen.',
    date: '11. April 2026',
    readTime: '12 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'hauskauf-vorbereiten',
    title: 'Hauskauf vorbereiten: Welche Daten Sie vor der Besichtigung prüfen sollten',
    description: 'Exposé auswerten, Lage recherchieren, Finanzen durchrechnen — die 60-Minuten-Vorprüfung die Ihnen teure Fehlbesichtigungen erspart.',
    date: '11. April 2026',
    readTime: '11 Min',
    tags: ['Checkliste', 'Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'immobilien-vergleichen',
    title: 'Immobilien vergleichen: Welche Kennzahlen wirklich aussagekräftig sind',
    description: 'Kaufpreis, Quadratmeterpreis, Energieklasse — welche 8 Kennzahlen einen echten Vergleich ermöglichen und welche Fehler Sie vermeiden sollten.',
    date: '11. April 2026',
    readTime: '11 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1464082354059-27db6ce50048?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'sanierungsbedarf-erkennen',
    title: 'Sanierungsbedarf erkennen: Erste Hinweise schon im Exposé',
    description: 'Baujahr, Energieklasse, fehlende Sanierungsangaben — welche Exposé-Signale auf versteckte Kosten hindeuten und was Sanierung wirklich kostet.',
    date: '11. April 2026',
    readTime: '12 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'lagebewertung-hauskauf',
    title: 'Lagebewertung beim Hauskauf: Warum die Adresse allein nicht reicht',
    description: 'Makrolage, Mikrolage, Lärmkarten, Hochwasserrisiko — welche 8 Lagefaktoren den Immobilienwert wirklich bestimmen und wie Sie sie prüfen.',
    date: '11. April 2026',
    readTime: '11 Min',
    tags: ['Standort', 'Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1464082354059-27db6ce50048?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'kaufnebenkosten-immobilienkauf',
    title: 'Kaufnebenkosten beim Immobilienkauf: Was Käufer oft unterschätzen',
    description: 'Grunderwerbsteuer, Notar, Makler — und dann noch Sanierung, Umzug und Sonderumlagen. So berechnen Sie die wahren Kosten eines Immobilienkaufs.',
    date: '11. April 2026',
    readTime: '10 Min',
    tags: ['Finanzierung', 'Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'energieausweis-expose',
    title: 'Energieausweis im Exposé: Was die Werte über eine Immobilie verraten',
    description: 'Verbrauchsausweis vs. Bedarfsausweis, Effizienzklassen A+ bis H, Heizkosten berechnen und typische Missverständnisse — so bewerten Sie Energiekennwerte richtig.',
    date: '11. April 2026',
    readTime: '11 Min',
    tags: ['Energie', 'Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'warnsignale-expose',
    title: 'Warnsignale im Immobilien-Exposé: Diese Punkte sollten Sie ernst nehmen',
    description: 'Fehlende Daten, Maklerfloskeln, unrealistische Preise — welche Warnsignale sofort misstrauisch machen und welche erst im Zusammenspiel kritisch werden.',
    date: '11. April 2026',
    readTime: '10 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1560440021-33f9b867899d?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'quadratmeterpreis-bewerten',
    title: 'Quadratmeterpreis bewerten: Wann eine Immobilie zu teuer ist',
    description: 'Warum Vergleichswerte allein irreführend sind und welche 7 Faktoren den fairen Quadratmeterpreis bestimmen.',
    date: '11. April 2026',
    readTime: '9 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'expose-pruefen',
    title: 'Immobilien-Exposé prüfen: Worauf Käufer wirklich achten sollten',
    description: 'Systematisch Exposés auswerten: Kennzahlen, Maklersprache, Red Flags und die Fragen, die Sie vor der Besichtigung stellen müssen.',
    date: '11. April 2026',
    readTime: '10 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&h=450&fit=crop&auto=format&q=80',
  },
]

// Map slug → lazy component (filled as posts are written)
export const POST_COMPONENTS: Record<string, React.LazyExoticComponent<React.ComponentType>> = {
  'expose-pruefen': lazy(() => import('./expose-pruefen')),
  'quadratmeterpreis-bewerten': lazy(() => import('./quadratmeterpreis-bewerten')),
  'warnsignale-expose': lazy(() => import('./warnsignale-expose')),
  'energieausweis-expose': lazy(() => import('./energieausweis-expose')),
  'kaufnebenkosten-immobilienkauf': lazy(() => import('./kaufnebenkosten-immobilienkauf')),
  'lagebewertung-hauskauf': lazy(() => import('./lagebewertung-hauskauf')),
  'sanierungsbedarf-erkennen': lazy(() => import('./sanierungsbedarf-erkennen')),
  'immobilien-vergleichen': lazy(() => import('./immobilien-vergleichen')),
  'hauskauf-vorbereiten': lazy(() => import('./hauskauf-vorbereiten')),
  'exposes-richtig-lesen': lazy(() => import('./exposes-richtig-lesen')),
  'was-im-expose-fehlt': lazy(() => import('./was-im-expose-fehlt')),
  'expose-analyse-vor-besichtigung': lazy(() => import('./expose-analyse-vor-besichtigung')),
  'angebotspreis-fair': lazy(() => import('./angebotspreis-fair')),
  'immobilienbewertung-kaeufer': lazy(() => import('./immobilienbewertung-kaeufer')),
  'hauskauf-mit-system': lazy(() => import('./hauskauf-mit-system')),
  'fehler-immobilienkauf': lazy(() => import('./fehler-immobilienkauf')),
  'immobilien-check-vor-kauf': lazy(() => import('./immobilien-check-vor-kauf')),
  'baujahr-einordnen': lazy(() => import('./baujahr-einordnen')),
  'zustand-folgekosten': lazy(() => import('./zustand-folgekosten')),
  'besichtigung-vorbereitung': lazy(() => import('./besichtigung-vorbereitung')),
  'expose-verstehen': lazy(() => import('./expose-verstehen')),
  'immobilien-realistischer-einordnen': lazy(() => import('./immobilien-realistischer-einordnen')),
  'daten-statt-bauchgefuehl': lazy(() => import('./daten-statt-bauchgefuehl')),
  'eigentumswohnung-kaufen-expose': lazy(() => import('./eigentumswohnung-kaufen-expose')),
  'einfamilienhaus-kaufen-expose': lazy(() => import('./einfamilienhaus-kaufen-expose')),
  'fehler-private-kaeufer': lazy(() => import('./fehler-private-kaeufer')),
  'zustand-richtig-einschaetzen': lazy(() => import('./zustand-richtig-einschaetzen')),
  'baujahr-und-modernisierung': lazy(() => import('./baujahr-und-modernisierung')),
  'grundriss-richtig-lesen': lazy(() => import('./grundriss-richtig-lesen')),
  'wohnflaeche-richtig-einordnen': lazy(() => import('./wohnflaeche-richtig-einordnen')),
  'hausgeld-ruecklagen-sonderumlage': lazy(() => import('./hausgeld-ruecklagen-sonderumlage')),
  'bilder-im-expose-bewerten': lazy(() => import('./bilder-im-expose-bewerten')),
  'nebenkosten-laufende-kosten': lazy(() => import('./nebenkosten-laufende-kosten')),
  'infrastruktur-pruefen': lazy(() => import('./infrastruktur-pruefen')),
  'immobilienkauf-mit-familie': lazy(() => import('./immobilienkauf-mit-familie')),
  'unterlagen-vor-immobilienkauf': lazy(() => import('./unterlagen-vor-immobilienkauf')),
  'immobilienanfragen-bearbeiten': lazy(() => import('./immobilienanfragen-bearbeiten')),
  'fristen-immobilienkauf': lazy(() => import('./fristen-immobilienkauf')),
  'rauchen-dampfen-wohnqualitaet': lazy(() => import('./rauchen-dampfen-wohnqualitaet')),
}
