import { lazy } from 'react'
import type { BlogMeta } from '../BlogLayout'

// Blog posts registry — newest first
export const BLOG_POSTS: BlogMeta[] = [
  {
    slug: 'grundsteuer-reform-2025-2026',
    title: 'Grundsteuer 2026 nach der Reform: Was Käufer zahlen',
    description: 'Grundsteuer 2026 nach der Reform: Berechnung, Bundes- vs. Ländermodelle, Hebesätze und wie Käufer die jährliche Belastung vor dem Kauf richtig abschätzen.',
    date: '15. Juni 2026',
    readTime: '8 Min',
    tags: ['Kaufratgeber', 'Finanzierung'],
    image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'wohngebaeudeversicherung-hauskauf',
    title: 'Wohngebäudeversicherung beim Hauskauf 2026: Pflicht & Kosten',
    description: 'Wohngebäudeversicherung beim Hauskauf: keine Pflicht, aber von der Bank verlangt. §95 VVG, Sonderkündigungsrecht, Elementarschutz & Prämie 2026 erklärt.',
    date: '15. Juni 2026',
    readTime: '8 Min',
    tags: ['Kaufratgeber', 'Finanzierung'],
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'geg-sanierungspflichten-altbau-kauf',
    title: 'GEG-Sanierungspflichten beim Altbau-Kauf 2026',
    description: 'Heizkessel, Dachdämmung, Rohrleitungen: Welche GEG-Pflichten beim Altbau-Kauf 2026 greifen, welche Fristen gelten und was Käufer jetzt tun sollten.',
    date: '15. Juni 2026',
    readTime: '8 Min',
    tags: ['Kaufratgeber', 'Zustand'],
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'photovoltaik-immobilie-bewerten',
    title: 'Photovoltaik beim Hauskauf bewerten: Eigentum oder Pacht?',
    description: 'PV-Anlage beim Hauskauf prüfen: Eigentum oder Pachtvertrag, Alter von Modulen und Wechselrichter, EEG-Vergütung 2026 und 0 % Steuer einfach erklärt.',
    date: '15. Juni 2026',
    readTime: '9 Min',
    tags: ['Kaufratgeber', 'Zustand'],
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'risse-im-mauerwerk-beurteilen',
    title: 'Risse im Mauerwerk beurteilen: harmlos oder Risiko?',
    description: 'Putzriss oder statisches Risiko? So erkennen Sie gefährliche Risse im Mauerwerk, prüfen mit Gipsmarke aktive Risse und wissen, wann der Statiker muss.',
    date: '15. Juni 2026',
    readTime: '8 Min',
    tags: ['Kaufratgeber', 'Zustand'],
    image: 'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'elektroinstallation-altbau-pruefen',
    title: 'Elektroinstallation im Altbau prüfen: FI-Schalter & Kosten',
    description: 'Elektroinstallation im Altbau prüfen: Warnzeichen am Sicherungskasten, FI-Schalter-Pflicht, E-Check und realistische Kosten der Sanierung im Überblick.',
    date: '15. Juni 2026',
    readTime: '8 Min',
    tags: ['Kaufratgeber', 'Zustand'],
    image: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'haus-geerbt-verkaufen-vermieten',
    title: 'Haus geerbt: verkaufen, vermieten oder selbst nutzen?',
    description: 'Geerbtes Haus 2026: Erbschaftsteuer-Freibeträge, Familienheim-Befreiung, Spekulationssteuer, Erbengemeinschaft und Grundbuch – verständlich erklärt.',
    date: '15. Juni 2026',
    readTime: '9 Min',
    tags: ['Kaufratgeber', 'Finanzierung'],
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'wohnrecht-niessbrauch-immobilie-kaufen',
    title: 'Wohnrecht und Nießbrauch: Immobilie mit Belastung kaufen',
    description: 'Wohnrecht (§ 1093) oder Nießbrauch (§ 1030) im Grundbuch? So mindern sie den Wert, das droht Käufern – und so prüfen Sie ein belastetes Objekt richtig.',
    date: '15. Juni 2026',
    readTime: '9 Min',
    tags: ['Kaufratgeber', 'Checkliste'],
    image: 'https://images.unsplash.com/photo-1551836022-deb4988cc6c0?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'bausparvertrag-immobilienkauf',
    title: 'Bausparvertrag für den Immobilienkauf: Lohnt er sich?',
    description: 'Bausparvertrag beim Immobilienkauf: Wie Sparphase, Darlehensphase und Zinssicherheit funktionieren, welche Förderung möglich ist und für wen er sich lohnt.',
    date: '13. Juni 2026',
    readTime: '8 Min',
    tags: ['Kaufratgeber', 'Finanzierung'],
    image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'bausachverstaendiger-hauskauf-kosten',
    title: 'Bausachverständiger beim Hauskauf: Kosten und Nutzen',
    description: 'Bausachverständiger beim Hauskauf: Was ein Baugutachter kostet (rund 300 bis 2.000 €), was er leistet und wann sich das Gutachten für private Käufer lohnt.',
    date: '13. Juni 2026',
    readTime: '7 Min',
    tags: ['Kaufratgeber', 'Zustand'],
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'uebergabeprotokoll-hauskauf',
    title: 'Übergabeprotokoll beim Hauskauf: Checkliste für die Übergabe',
    description: 'Übergabeprotokoll beim Hauskauf: Welche Zählerstände, Schlüssel und Unterlagen gehören hinein? Mit Checkliste für eine sichere Übergabe ohne späteren Streit.',
    date: '13. Juni 2026',
    readTime: '8 Min',
    tags: ['Kaufratgeber', 'Checkliste'],
    image: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'dach-pruefen-hauskauf',
    title: 'Dach prüfen beim Hauskauf: Zustand, Alter und Kosten',
    description: 'Dach prüfen beim Hauskauf: So erkennen Sie Schäden, schätzen das Alter richtig ein und kalkulieren Sanierungskosten von 20.000 bis 50.000 € realistisch.',
    date: '13. Juni 2026',
    readTime: '8 Min',
    tags: ['Kaufratgeber', 'Zustand'],
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'asbest-im-haus-erkennen',
    title: 'Asbest im Haus erkennen: Risiko prüfen und richtig handeln',
    description: 'Asbest im Haus erkennen: Wo der Baustoff steckt, wann er gefährlich wird, was Probe und Sanierung kosten und wie Käufer von Häusern 1950 bis 1990 vorgehen.',
    date: '13. Juni 2026',
    readTime: '7 Min',
    tags: ['Kaufratgeber', 'Zustand'],
    image: 'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'hochwasser-risiko-immobilie-pruefen',
    title: 'Hochwasserrisiko einer Immobilie prüfen: so geht es',
    description: 'Hochwasserrisiko vor dem Kauf prüfen: kostenlose Gefahrenkarten, HQ100, ZÜRS-Klassen GK1 bis GK4 und warum nur die Elementarschadenversicherung schützt.',
    date: '13. Juni 2026',
    readTime: '9 Min',
    tags: ['Kaufratgeber', 'Standort'],
    image: 'https://images.unsplash.com/photo-1551836022-deb4988cc6c0?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'neubau-bautraeger-vertrag-mabv',
    title: 'Neubau vom Bauträger: Vertrag und Abschläge nach MaBV',
    description: 'Bauträgervertrag und Abschläge nach MaBV: bis zu 13 Raten nach Baufortschritt, Sicherungen vor der ersten Rate, 5 Jahre Gewährleistung nach § 634a BGB.',
    date: '13. Juni 2026',
    readTime: '8 Min',
    tags: ['Kaufratgeber', 'Checkliste'],
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'grundstueck-kaufen-worauf-achten',
    title: 'Grundstück kaufen: Worauf Sie vor dem Bau achten müssen',
    description: 'Grundstück kaufen leicht gemacht: Bebaubarkeit, Erschließung, Baugrund, Grundbuch und Grunderwerbsteuer im Überblick. So vermeiden Sie teure Fehler vor dem Bau.',
    date: '13. Juni 2026',
    readTime: '8 Min',
    tags: ['Kaufratgeber', 'Standort'],
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'zwangsversteigerung-immobilie-kaufen',
    title: 'Zwangsversteigerung: Immobilie ersteigern – so gelingt es',
    description: 'Zwangsversteigerung einer Immobilie: Wie das Verfahren nach ZVG abläuft, welche Wertgrenzen gelten, was Sie sparen und welche Risiken Sie vorab prüfen sollten.',
    date: '13. Juni 2026',
    readTime: '8 Min',
    tags: ['Kaufratgeber', 'Finanzierung'],
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'bodenrichtwert-verstehen-abfragen',
    title: 'Bodenrichtwert verstehen und kostenlos abfragen 2026',
    description: 'Bodenrichtwert verstehen: Was die amtliche Kennzahl aussagt, wie Sie sie über BORIS kostenlos abfragen und den Grundstücksanteil am Kaufpreis prüfen.',
    date: '13. Juni 2026',
    readTime: '8 Min',
    tags: ['Kaufratgeber', 'Standort'],
    image: 'https://images.unsplash.com/photo-1551836022-deb4988cc6c0?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'notartermin-ablauf-hauskauf',
    title: 'Notartermin beim Hauskauf: Ablauf Schritt für Schritt',
    description: 'Notartermin beim Hauskauf: So läuft die Beurkundung ab. Prüffrist, Verlesen, Auflassungsvormerkung, Kaufpreiszahlung und Kosten verständlich erklärt.',
    date: '13. Juni 2026',
    readTime: '8 Min',
    tags: ['Kaufratgeber', 'Checkliste'],
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'kaufvertrag-immobilie-pruefen',
    title: 'Kaufvertrag Immobilie prüfen: Diese Klauseln sind wichtig',
    description: 'Immobilien-Kaufvertrag prüfen: Pflichtbestandteile, Gewährleistungsausschluss nach § 444 BGB, Inventar-Ausweis zur Steuerersparnis und die 14-tägige Prüffrist.',
    date: '13. Juni 2026',
    readTime: '8 Min',
    tags: ['Kaufratgeber', 'Checkliste'],
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'erbbaurecht-erbpacht-kaufen',
    title: 'Erbbaurecht (Erbpacht): Haus auf fremdem Grund kaufen',
    description: 'Erbbaurecht statt Grundstückskauf: Wie der Erbbauzins funktioniert, was beim Heimfall passiert und worauf Käufer bei Laufzeit und Vertrag achten sollten.',
    date: '13. Juni 2026',
    readTime: '8 Min',
    tags: ['Kaufratgeber', 'Finanzierung'],
    image: 'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'schimmel-feuchtigkeit-hauskauf',
    title: 'Schimmel und Feuchtigkeit beim Hauskauf richtig erkennen',
    description: 'Schimmel und Feuchtigkeit beim Hauskauf erkennen: Ursachen, Warnzeichen bei der Besichtigung, Sanierungskosten und worauf Käufer rechtlich achten sollten.',
    date: '13. Juni 2026',
    readTime: '8 Min',
    tags: ['Kaufratgeber', 'Zustand'],
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'heizungsarten-vergleich-kosten',
    title: 'Heizungsarten im Vergleich: Kosten, Eignung, Zukunft',
    description: 'Heizungsarten im Vergleich: Was Wärmepumpe, Gas, Pellets und Fernwärme bei Anschaffung, Betriebskosten und Zukunftssicherheit für Käufer wirklich bedeuten.',
    date: '13. Juni 2026',
    readTime: '9 Min',
    tags: ['Kaufratgeber', 'Energie'],
    image: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'reservierungsgebuehr-immobilie',
    title: 'Reservierungsgebühr Immobilie: zahlen oder lieber nicht?',
    description: 'Reservierungsgebühr beim Immobilienkauf: Was sie kostet, warum der BGH sie kritisch sieht und wann Sie gezahlte Gebühren zurückfordern können – ein Überblick.',
    date: '13. Juni 2026',
    readTime: '8 Min',
    tags: ['Kaufratgeber', 'Finanzierung'],
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'vorfaelligkeitsentschaedigung',
    title: 'Vorfälligkeitsentschädigung: Wann sie anfällt und wie hoch',
    description: 'Vorfälligkeitsentschädigung bei vorzeitiger Darlehensablösung: Wann sie anfällt, wie hoch sie ist, wann sie entfällt und wie Sie die Berechnung prüfen lassen.',
    date: '13. Juni 2026',
    readTime: '7 Min',
    tags: ['Kaufratgeber', 'Finanzierung'],
    image: 'https://images.unsplash.com/photo-1551836022-deb4988cc6c0?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'grundschuld-vs-hypothek',
    title: 'Grundschuld oder Hypothek: Der Unterschied einfach erklärt',
    description: 'Grundschuld oder Hypothek: Was ist der Unterschied? Warum die Grundschuld heute Standard ist, was nach der Tilgung passiert und worauf Käufer achten sollten.',
    date: '13. Juni 2026',
    readTime: '7 Min',
    tags: ['Kaufratgeber', 'Finanzierung'],
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'kfw-wohneigentum-familien-2026',
    title: 'KfW-Förderung für Familien 2026: günstig zum Wohneigentum',
    description: 'KfW-Förderung für Familien 2026: Voraussetzungen, Einkommensgrenze von 90.000 €, Effizienzhaus 40 mit QNG, Unterschied WEF (300) und Programm 124 sowie Tipps zum Antrag.',
    date: '13. Juni 2026',
    readTime: '8 Min',
    tags: ['Kaufratgeber', 'Finanzierung'],
    image: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'bonitaet-schufa-baufinanzierung',
    title: 'Bonität und SCHUFA bei der Baufinanzierung im Blick',
    description: 'Bonität und SCHUFA bei der Baufinanzierung: Was Banken prüfen, wie der Score den Zins beeinflusst und wie Sie sich mit Datenkopie und Konditionsanfrage vorbereiten.',
    date: '13. Juni 2026',
    readTime: '8 Min',
    tags: ['Kaufratgeber', 'Finanzierung'],
    image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'erschliessungskosten-erschliessungsbeitrag',
    title: 'Erschließungskosten beim Grundstückskauf: Wer zahlt was?',
    description: 'Erschließungskosten und Erschließungsbeitrag verstehen: Wer zahlt Straße und Hausanschlüsse, welche Nachzahlungen drohen und was Sie vor dem Kauf klären müssen.',
    date: '13. Juni 2026',
    readTime: '8 Min',
    tags: ['Kaufratgeber', 'Finanzierung'],
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'vorkaufsrecht-gemeinde-milieuschutz',
    title: 'Vorkaufsrecht der Gemeinde und Milieuschutz beim Kauf',
    description: 'Vorkaufsrecht der Gemeinde und Milieuschutz beim Immobilienkauf: Wann es greift, wie der Ablauf nach der Beurkundung aussieht und worauf Käufer achten müssen.',
    date: '13. Juni 2026',
    readTime: '8 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'baulasten-grunddienstbarkeiten',
    title: 'Baulasten und Grunddienstbarkeiten: versteckte Lasten erkennen',
    description: 'Baulasten und Grunddienstbarkeiten erkennen: wo sie stehen, wie sie Wert und Bebaubarkeit mindern und wie Käufer Grundbuch und Baulastenverzeichnis prüfen.',
    date: '13. Juni 2026',
    readTime: '8 Min',
    tags: ['Kaufratgeber', 'Checkliste'],
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'auflassungsvormerkung-erklaert',
    title: 'Auflassungsvormerkung: So sind Sie beim Kauf abgesichert',
    description: 'Auflassungsvormerkung einfach erklärt: Wie § 883 BGB Ihren Anspruch sichert, warum Sie erst nach Eintragung zahlen und was Auflassung und Eintragung trennt.',
    date: '13. Juni 2026',
    readTime: '7 Min',
    tags: ['Kaufratgeber', 'Checkliste'],
    image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'wohnung-kaufen-vermieten-kapitalanlage',
    title: 'Wohnung kaufen und vermieten: Einstieg in die Kapitalanlage',
    description: 'Wohnung kaufen und vermieten als Kapitalanlage: So berechnen Sie Mietrendite, Cashflow und Steuern, planen Risiken ein und prüfen Angebote vor dem Kauf.',
    date: '13. Juni 2026',
    readTime: '8 Min',
    tags: ['Kaufratgeber', 'Finanzierung'],
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'denkmalschutz-immobilie-kaufen',
    title: 'Denkmalschutz-Immobilie kaufen: Auflagen, Kosten, Denkmal-AfA',
    description: 'Denkmalgeschützte Immobilie kaufen: Welche Auflagen gelten, warum die Sanierung teurer ist und wie die Denkmal-AfA bei Vermietung und Eigennutzung funktioniert.',
    date: '13. Juni 2026',
    readTime: '8 Min',
    tags: ['Kaufratgeber', 'Zustand'],
    image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'hauskauf-ohne-eigenkapital',
    title: 'Hauskauf ohne Eigenkapital: Geht das – und für wen?',
    description: 'Hauskauf ohne Eigenkapital: Was 100- und 110-Prozent-Finanzierung bedeuten, welcher Zinsaufschlag droht, Beispielrechnung für 400.000 € und für wen sich die Vollfinanzierung lohnt.',
    date: '13. Juni 2026',
    readTime: '7 Min',
    tags: ['Kaufratgeber', 'Finanzierung'],
    image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'annuitaetendarlehen-erklaert',
    title: 'Annuitätendarlehen erklärt: Zins, Tilgung und Rate',
    description: 'Annuitätendarlehen einfach erklärt: Wie sich Zins, Tilgung und die monatliche Rate zusammensetzen, plus Faustformel und Beispielrechnung für private Käufer.',
    date: '13. Juni 2026',
    readTime: '7 Min',
    tags: ['Kaufratgeber', 'Finanzierung'],
    image: 'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'sondertilgung-sinnvoll',
    title: 'Sondertilgung: Wann sie sich lohnt und wann nicht',
    description: 'Sondertilgung sinnvoll? Wie sie Zinsen spart und die Laufzeit verkürzt, ein Rechenbeispiel, die Abwägung Tilgen oder Anlegen und wann Sie besser warten.',
    date: '13. Juni 2026',
    readTime: '7 Min',
    tags: ['Kaufratgeber', 'Finanzierung'],
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'zinsbindung-10-oder-15-jahre',
    title: 'Zinsbindung 10 oder 15 Jahre? Die Entscheidungshilfe',
    description: 'Zinsbindung 10 oder 15 Jahre? Mit Beispielrechnung, dem Sonderkündigungsrecht nach 10 Jahren laut Paragraf 489 BGB und klarer Faustregel zur Entscheidung.',
    date: '13. Juni 2026',
    readTime: '7 Min',
    tags: ['Kaufratgeber', 'Finanzierung'],
    image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'anschlussfinanzierung-forward-darlehen',
    title: 'Anschlussfinanzierung & Forward-Darlehen einfach erklärt',
    description: 'Anschlussfinanzierung erklärt: Prolongation oder Umschuldung, wie ein Forward-Darlehen den Zins sichert, Rechenbeispiel und der richtige Zeitpunkt.',
    date: '13. Juni 2026',
    readTime: '8 Min',
    tags: ['Kaufratgeber', 'Finanzierung'],
    image: 'https://images.unsplash.com/photo-1619468129361-605ebea04b44?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'bieterverfahren-immobilie',
    title: 'Bieterverfahren beim Immobilienkauf: Regeln und Strategie',
    description: 'Bieterverfahren beim Immobilienkauf verstehen: Wie Gebote ablaufen, warum sie bis zum Notar unverbindlich sind und wie Sie mit klarem Limit klug bieten.',
    date: '13. Juni 2026',
    readTime: '7 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'provisionsfrei-immobilie-bedeutung',
    title: 'Provisionsfrei: Was es bedeutet und ob es günstiger ist',
    description: 'Provisionsfrei beim Immobilienkauf: Was das Label bedeutet, die 50/50-Regel seit 2020 und warum ein provisionsfreies Objekt nicht automatisch günstiger ist.',
    date: '13. Juni 2026',
    readTime: '7 Min',
    tags: ['Kaufratgeber', 'Finanzierung'],
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'grundbuch-lesen',
    title: 'Grundbuch lesen: Abteilungen I, II und III einfach erklärt',
    description: 'Grundbuch lesen leicht gemacht: Was in Abteilung I, II und III steht, worauf Käufer bei Lasten und Grundschulden achten und wie Sie an einen Auszug kommen.',
    date: '13. Juni 2026',
    readTime: '8 Min',
    tags: ['Kaufratgeber', 'Checkliste'],
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'teilungserklaerung-pruefen',
    title: 'Teilungserklärung prüfen: Worauf ETW-Käufer achten müssen',
    description: 'Teilungserklärung prüfen vor dem Wohnungskauf: Sondereigentum, Gemeinschaftseigentum, Miteigentumsanteile und Sondernutzungsrechte verständlich erklärt.',
    date: '13. Juni 2026',
    readTime: '8 Min',
    tags: ['Kaufratgeber', 'Checkliste'],
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'energetische-sanierung-foerderung-2026',
    title: 'Sanierung fördern lassen 2026: KfW, BAFA und Boni im Überblick',
    description: 'Energetische Sanierung 2026 fördern lassen: bis zu 70 % Zuschuss beim Heizungstausch, 15–20 % vom BAFA, Boni und Kredite — mit Beispielrechnungen für Käufer.',
    date: '13. Juni 2026',
    readTime: '8 Min',
    tags: ['Kaufratgeber', 'Energie'],
    image: 'https://images.unsplash.com/photo-1593476550610-87baa860004a?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'grunderwerbsteuer-2026-bundeslaender',
    title: 'Grunderwerbsteuer 2026: Tabelle aller Bundesländer + Spartipps',
    description: 'Grunderwerbsteuer 2026 im Überblick: Steuersätze aller 16 Bundesländer als Tabelle, Beispielrechnung für 400.000 € Kaufpreis und 5 legale Spartipps für Käufer.',
    date: '12. Juni 2026',
    readTime: '7 Min',
    tags: ['Kaufratgeber', 'Finanzierung'],
    image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'hauskauf-checkliste-2026',
    title: 'Hauskauf-Checkliste 2026: Alle 12 Schritte bis zur Übergabe',
    description: 'Hauskauf-Checkliste 2026: alle 12 Schritte von Budget und Besichtigung über Finanzierung und Notartermin bis zur Übergabe — mit realistischem Zeitplan und Fristen.',
    date: '12. Juni 2026',
    readTime: '8 Min',
    tags: ['Kaufratgeber', 'Checkliste'],
    image: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'kaufen-oder-mieten-2026',
    title: 'Kaufen oder Mieten 2026: Rechenweg statt Bauchgefühl',
    description: 'Kaufen oder Mieten 2026? Mit Kaufpreisfaktor, Vollkostenrechnung und 20-Jahres-Vergleich treffen Sie die Entscheidung auf Zahlenbasis statt nach Bauchgefühl.',
    date: '12. Juni 2026',
    readTime: '8 Min',
    tags: ['Kaufratgeber', 'Finanzierung'],
    image: 'https://images.unsplash.com/photo-1560440021-33f9b867899d?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'maklerprovision-immobilienkauf',
    title: 'Maklerprovision beim Immobilienkauf: Wer zahlt wie viel?',
    description: 'Maklerprovision beim Immobilienkauf: 50/50-Regel seit 2020, übliche Sätze von 2,98 bis 3,57 % für Käufer, Beispielrechnungen und was wirklich verhandelbar ist.',
    date: '12. Juni 2026',
    readTime: '7 Min',
    tags: ['Kaufratgeber', 'Finanzierung'],
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'notarkosten-grundbuchkosten-immobilienkauf',
    title: 'Notarkosten und Grundbuchkosten beim Hauskauf: Höhe und Beispiele',
    description: 'Notar- und Grundbuchkosten beim Immobilienkauf: Faustregeln von 1,5 bis 2 %, Beispielrechnungen für 300.000 bis 500.000 €, Ablauf, Zuständigkeiten und Sparpotenzial.',
    date: '12. Juni 2026',
    readTime: '7 Min',
    tags: ['Kaufratgeber', 'Finanzierung'],
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'eigenkapital-immobilienkauf',
    title: 'Eigenkapital beim Immobilienkauf: Wie viel ist 2026 nötig?',
    description: 'Wie viel Eigenkapital braucht der Immobilienkauf? Rechenbeispiele für 10, 20 und 30 % Quote, Zinseffekte, Faustregeln zur tragbaren Rate und Strategien bei wenig Kapital.',
    date: '12. Juni 2026',
    readTime: '7 Min',
    tags: ['Kaufratgeber', 'Finanzierung'],
    image: 'https://images.unsplash.com/photo-1464082354059-27db6ce50048?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'kaufpreisfaktor-mietrendite',
    title: 'Kaufpreisfaktor und Mietrendite: Immobilienpreise einordnen',
    description: 'Kaufpreisfaktor berechnen und einordnen: Formel, Tabelle von günstig bis teuer, Brutto- und Nettomietrendite mit Beispielrechnung — und die Grenzen der Kennzahl.',
    date: '12. Juni 2026',
    readTime: '7 Min',
    tags: ['Kaufratgeber', 'Finanzierung'],
    image: 'https://images.unsplash.com/photo-1551836022-deb4988cc6c0?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'altbau-oder-neubau-kaufen',
    title: 'Altbau oder Neubau kaufen? Kosten und Risiken im Vergleich',
    description: 'Altbau oder Neubau? Der ehrliche Vergleich: Kaufpreisunterschied, Sanierungskosten nach Baujahr, GEG-Pflichten nach dem Kauf, Förderung und Gewährleistung im Überblick.',
    date: '12. Juni 2026',
    readTime: '8 Min',
    tags: ['Kaufratgeber', 'Zustand'],
    image: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'innenausbau-bewerten',
    title: 'Innenausbau bewerten beim Hauskauf: Bodenbeläge, Materialien & Folgekosten',
    description: 'Fliesen, Parkett, Laminat, Vinyl, Teppich im Vergleich + Wände, Türen, Sanitär, Heizkörper. So schätzen Käufer die Innenausbau-Qualität ein und kalkulieren Renovierungskosten.',
    date: '22. April 2026',
    readTime: '14 Min',
    tags: ['Kaufratgeber', 'Zustand'],
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'fliesen-qualitaetsmerkmal-immobilie',
    title: 'Fliesen-Qualität beim Immobilienkauf: Material, Verlegung & Sanierungskosten prüfen',
    description: 'Material (Feinsteinzeug, Naturstein), Verlegung, Fugenzustand, Rutschklasse, Asbest-Risiko bei Altbauten — was Fliesen über Bausubstanz und Modernisierungsstand verraten.',
    date: '22. April 2026',
    readTime: '13 Min',
    tags: ['Kaufratgeber', 'Zustand'],
    image: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'raeume-richtig-nutzen',
    title: 'Grundriss und Nutzung beim Hauskauf: Wegeführung, Möblierung & Flexibilität prüfen',
    description: 'Wegeführung, Möbelmaße, Wohn-Ess-Zentrum, Rückzug, Flexibilität über Lebensphasen — 8 Nutzungs-Aspekte, die im Grundriss erkennbar sind, mit konkreter Möbelmaß-Tabelle.',
    date: '22. April 2026',
    readTime: '13 Min',
    tags: ['Kaufratgeber', 'Grundriss'],
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'wohnqualitaet-bewerten',
    title: 'Wohnqualität bei Immobilien bewerten: 8 Alltagsfaktoren über Preis und Fläche hinaus',
    description: 'Raumaufteilung, Tageslicht, Lärm, Lage, Flexibilität, Stauraum, Außenflächen, Klima — 8 Wohnqualitäts-Faktoren, die klassische Kennzahlen nicht abdecken.',
    date: '22. April 2026',
    readTime: '14 Min',
    tags: ['Kaufratgeber', 'Standort'],
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'homeoffice-immobilienkauf',
    title: 'Homeoffice beim Hauskauf: Welche Immobilie eignet sich für Arbeiten zu Hause?',
    description: 'Grundriss, Tageslicht, Lärm, Internet-Anschluss, flexible Raumnutzung — 8 Prüfpunkte, ob eine Immobilie langfristig homeoffice-tauglich ist und wie das die Bewertung beeinflusst.',
    date: '22. April 2026',
    readTime: '13 Min',
    tags: ['Kaufratgeber', 'Grundriss'],
    image: 'https://images.unsplash.com/photo-1593476550610-87baa860004a?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'rauchen-dampfen-wohnqualitaet',
    title: 'Rauchen und Dampfen in der Wohnung: Welche Spuren bleiben — und was die Sanierung kostet',
    description: 'Gerüche, Verfärbungen, Nikotin- und Dampfrückstände auf Wand, Decke, Tapete — wie sich Rauchspuren bei der Besichtigung erkennen lassen und welche Sanierungskosten realistisch sind.',
    date: '19. April 2026',
    readTime: '13 Min',
    tags: ['Kaufratgeber', 'Besichtigung'],
    image: 'https://images.unsplash.com/photo-1522444195799-478538b28823?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'fristen-immobilienkauf',
    title: 'Fristen beim Immobilienkauf: Kaufpreisfälligkeit, Bedenkzeit, Widerruf — alle Termine im Überblick',
    description: 'Notartermin, 14-tägige Bedenkzeit, Kaufpreisfälligkeit (typisch 10–14 Tage nach Fälligkeitsmitteilung), Widerrufsfristen, Übergabe — die 12 wichtigsten Fristen im Kaufprozess chronologisch erklärt mit Checkliste.',
    date: '19. April 2026',
    readTime: '14 Min',
    tags: ['Kaufratgeber', 'Checkliste'],
    image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'immobilienanfragen-bearbeiten',
    title: 'Immobilienanfragen bearbeiten: Wie Makler und Privatverkäufer Anfragen vorsortieren',
    description: 'Ampel-Raster für die Anfrage-Vorqualifikation, 5-Schritte-Prozess und sinnvolle Automatisierung — was Käufer aus dem Verkäufer-Workflow ableiten können.',
    date: '19. April 2026',
    readTime: '13 Min',
    tags: ['Kaufratgeber', 'Checkliste'],
    image: 'https://images.unsplash.com/photo-1551836022-deb4988cc6c0?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'unterlagen-vor-immobilienkauf',
    title: 'Welche Unterlagen vor dem Immobilienkauf prüfen? 12 Pflicht-Dokumente für ETW & Haus',
    description: 'Grundbuchauszug, Energieausweis, WEG-Protokolle, Teilungserklärung, Baulastenverzeichnis, Wohngeldabrechnung — die 12 wichtigsten Dokumente vor Notartermin, getrennt nach Eigentumswohnung und Einfamilienhaus mit Timeline.',
    date: '11. April 2026',
    readTime: '13 Min',
    tags: ['Checkliste', 'Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1560440021-33f9b867899d?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'immobilienkauf-mit-familie',
    title: 'Immobilienkauf mit Familie: Worauf Eltern und Großfamilien beim Hauskauf achten',
    description: 'Zimmeranzahl-Formel, familientauglicher Grundriss, Schulnähe, Garten, Sicherheit — 10 Familien-Kriterien, die mit Kindern wichtiger werden als ohne. Mit Checkliste.',
    date: '11. April 2026',
    readTime: '14 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'infrastruktur-pruefen',
    title: 'Infrastruktur beim Hauskauf prüfen: Supermarkt, ÖPNV, Schule, Arzt im Umfeld bewerten',
    description: '8 Infrastruktur-Bereiche mit Richtwerten in Minuten, eine Zielgruppen-Matrix für Singles, Familien und Senioren sowie ein 15-Minuten-Schnellcheck für die Mikrolage.',
    date: '11. April 2026',
    readTime: '13 Min',
    tags: ['Standort', 'Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1464082354059-27db6ce50048?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'nebenkosten-laufende-kosten',
    title: 'Laufende Kosten beim Hauskauf: Was Eigentümer monatlich wirklich zahlen (ETW & EFH)',
    description: 'Hausgeld, Grundsteuer, Versicherung, Heizkosten, Rücklage, Strom, Wasser — laufende Kosten bei Wohnung und Haus realistisch berechnen, mit Beispielrechnung über 20 Jahre und Tragbarkeits-Faustregel.',
    date: '11. April 2026',
    readTime: '14 Min',
    tags: ['Finanzierung', 'Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'bilder-im-expose-bewerten',
    title: 'Exposé-Fotos richtig bewerten: Weitwinkel, HDR und Home Staging entlarven',
    description: 'Wie Exposé-Bilder entstehen, welche Tricks Makler einsetzen (Weitwinkel, HDR, Staging) und welche Details Fotos wirklich verraten — vor der Besichtigung.',
    date: '11. April 2026',
    readTime: '13 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'hausgeld-ruecklagen-sonderumlage',
    title: 'Hausgeld, Rücklagen, Sonderumlage: Was Wohnungskäufer beim ETW-Kauf prüfen müssen',
    description: 'Hausgeld-Aufschlüsselung, Rücklage-Richtwerte (1–3 €/m²), Sonderumlage-Kosten und 3 typische WEG-Szenarien — der komplette ETW-Kosten-Guide für Eigentumswohnungs-Käufer.',
    date: '11. April 2026',
    readTime: '14 Min',
    tags: ['Finanzierung', 'Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'wohnflaeche-richtig-einordnen',
    title: 'Wohnfläche im Exposé richtig lesen: WoFlV, DIN 277 und typische Quadratmeter-Fallen',
    description: 'WoFlV vs. DIN 277, Dachschrägen-Anrechnung, Verkehrsflächen, Balkon-Anteil — warum 90 m² Wohnfläche im Exposé nicht gleich 90 m² nutzbare Fläche sind.',
    date: '11. April 2026',
    readTime: '13 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1619468129361-605ebea04b44?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'grundriss-richtig-lesen',
    title: 'Grundriss richtig lesen: Verkehrsflächen, Durchgangszimmer und Möblierbarkeit prüfen',
    description: '8 Prüfpunkte für jeden Immobilien-Grundriss: Verkehrsflächen, Durchgangszimmer, Möbel-Maße, Raumproportionen, tragende Wände, Anpassungs-Potenzial — mit Checkliste.',
    date: '11. April 2026',
    readTime: '13 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1619468129361-605ebea04b44?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'baujahr-und-modernisierung',
    title: 'Baujahr und Modernisierung zusammen bewerten: Was wirklich über den Zustand entscheidet',
    description: 'Gleiches Baujahr ≠ gleicher Zustand. Warum nur die Kombination aus Baujahr und Sanierungshistorie eine realistische Immobilien-Bewertung erlaubt — mit Beispielrechnungen.',
    date: '11. April 2026',
    readTime: '14 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'zustand-richtig-einschaetzen',
    title: 'Zustand einer Immobilie einschätzen: Exposé-Sprache und Besichtigung systematisch lesen',
    description: 'Zustandsbeschreibungen decoded, Foto-Analyse, Besichtigungs-Checkliste Raum für Raum und unsichtbare Mängel — den Zustand einer Immobilie realistisch einordnen.',
    date: '11. April 2026',
    readTime: '14 Min',
    tags: ['Kaufratgeber', 'Checkliste'],
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'fehler-private-kaeufer',
    title: 'Hauskauf-Fehler privater Käufer: 10 typische Irrtümer und ihre Folgekosten',
    description: 'Emotionale Bindung, unterschätzte Nebenkosten, Kauf unter Zeitdruck — 10 typische Käuferfehler beim Hauskauf mit konkreten Folgekosten und Vermeidungsstrategien.',
    date: '11. April 2026',
    readTime: '14 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'einfamilienhaus-kaufen-expose',
    title: 'Einfamilienhaus kaufen: Worauf Käufer im Exposé und beim Haus-Check achten',
    description: 'Dach, Heizung, Keller, Grundstück, Erschließung, Wegerechte — die EFH-spezifischen Prüfpunkte beim Hauskauf, die über Traumhaus oder Kostenfalle entscheiden.',
    date: '11. April 2026',
    readTime: '14 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'eigentumswohnung-kaufen-expose',
    title: 'Eigentumswohnung kaufen: Hausgeld, Rücklage, WEG und Teilungserklärung prüfen',
    description: 'Hausgeld, Rücklage, WEG-Protokolle, Teilungserklärung, Sonderumlagen — die ETW-spezifischen Daten, die über Kauf oder Fehlkauf einer Eigentumswohnung entscheiden.',
    date: '11. April 2026',
    readTime: '13 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'daten-statt-bauchgefuehl',
    title: 'Immobilien bewerten mit Daten statt Bauchgefühl: 10 Kennzahlen für Käufer',
    description: '10 Datenpunkte, die jeder Käufer kennen muss, ein 30-Minuten-Bewertungsprozess und warum Bauchgefühl ohne Fakten beim Hauskauf gefährlich ist.',
    date: '11. April 2026',
    readTime: '13 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1560440021-33f9b867899d?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'immobilien-realistischer-einordnen',
    title: 'Immobilie realistisch bewerten: Warum einzelne Kennzahlen Käufer täuschen können',
    description: '5 Kennzahlen, die isoliert betrachtet irreführen, 3 typische Denkfehler und wie Sie aus Einzelwerten eine belastbare Gesamteinschätzung der Immobilie ableiten.',
    date: '11. April 2026',
    readTime: '12 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'expose-verstehen',
    title: 'Immobilien-Exposé verstehen: Pflichtangaben, Wohnfläche und Quadratmeterpreise richtig lesen',
    description: 'Pflichtangaben (Energieausweis, Provision, Wohnfläche) vs. Werbe-Floskeln, typische Wohnfläche-Fallen, Quadratmeterpreis einordnen, Maklersprache übersetzt — Exposés in 5 Minuten sicher entschlüsseln.',
    date: '11. April 2026',
    readTime: '13 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1560440021-33f9b867899d?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'besichtigung-vorbereitung',
    title: 'Immobilien-Besichtigung vorbereiten: 30+ Fragen für Käufer vor Ort',
    description: '30+ konkrete Fragen für die Hausbesichtigung — sortiert nach 8 Themenbereichen (Bausubstanz, Heizung, WEG, Lage, Nachbarn etc.) mit Erklärung, warum jede Frage wichtig ist.',
    date: '11. April 2026',
    readTime: '13 Min',
    tags: ['Checkliste', 'Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'zustand-folgekosten',
    title: 'Zustand und Folgekosten: Warum günstige Immobilien teurer werden können',
    description: 'Die 20-Jahres-Rechnung: Warum eine 220.000-€-Wohnung über 20 Jahre genauso teuer werden kann wie eine 295.000-€-Immobilie. Mit Beispielrechnung und Sanierungskosten-Tabelle.',
    date: '11. April 2026',
    readTime: '12 Min',
    tags: ['Kaufratgeber', 'Finanzierung'],
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'baujahr-einordnen',
    title: 'Baujahr beim Immobilienkauf einordnen: Was es über Bauweise, Energie und Sanierung verrät',
    description: 'Von Gründerzeit bis GEG-Neubau: Was jede Bauepoche über Bauweise, Energieeffizienz, Schadstoffe (Asbest, KMF) und typischen Sanierungsbedarf verrät — Käufer-Guide.',
    date: '11. April 2026',
    readTime: '14 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'immobilien-check-vor-kauf',
    title: 'Immobilien-Check vor dem Kauf: 7 Prüfbereiche und 30-Minuten-Schnellcheck',
    description: '7 Prüfbereiche (Preis, Lage, Substanz, Energie, Finanzierung, Recht, Folgekosten), Ampelsystem und 30-Minuten-Schnellcheck — Risiken erkennen bevor sie zu Kosten werden.',
    date: '11. April 2026',
    readTime: '12 Min',
    tags: ['Checkliste', 'Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1560440021-33f9b867899d?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'fehler-immobilienkauf',
    title: 'Fehler beim Immobilienkauf: 10 teure Irrtümer und wie Käufer sie vermeiden',
    description: 'Unterschätzte Nebenkosten, ignorierter Energieausweis, Kauf unter Zeitdruck — 10 typische Hauskauf-Fehler mit konkreten Folgekosten und Vermeidungsstrategien.',
    date: '11. April 2026',
    readTime: '13 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'hauskauf-mit-system',
    title: 'Hauskauf mit System: Der 5-Phasen-Prozess für eine fundierte Kaufentscheidung',
    description: 'Anforderungs-Definition, Exposé-Vorprüfung, Besichtigung mit Checkliste, Bewertung, Verhandlung — der 5-Phasen-Hauskauf-Prozess Schritt für Schritt erklärt.',
    date: '11. April 2026',
    readTime: '13 Min',
    tags: ['Checkliste', 'Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'immobilienbewertung-kaeufer',
    title: 'Immobilienbewertung für Käufer: 10 Faktoren, die den Wert wirklich bestimmen',
    description: 'Lage, Zustand, Energieeffizienz, Baujahr, Grundriss, Mikrolage — die 10 Bewertungs-Faktoren von Profi-Gutachtern, in einer Käufer-tauglichen Erklärung.',
    date: '11. April 2026',
    readTime: '13 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'angebotspreis-fair',
    title: 'Angebotspreis fair? Wie Käufer prüfen, ob der Immobilienpreis realistisch ist',
    description: '3 Methoden zur Preiseinordnung (Vergleichswert, Sachwert, Ertragswert), 8 Faktoren des fairen Preises und ein Praxisbeispiel mit konkreter Berechnung.',
    date: '11. April 2026',
    readTime: '12 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'expose-analyse-vor-besichtigung',
    title: 'Exposé vor der Besichtigung analysieren: 3-Stufen-Filter spart dutzende Stunden',
    description: 'Das 3-Stufen-Filtersystem: Grundcheck (5 Min), Kennzahlen-Check (10 Min), Kontext-Recherche (15 Min) — so vermeiden Sie teure Fehlbesichtigungen.',
    date: '11. April 2026',
    readTime: '12 Min',
    tags: ['Checkliste', 'Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1560440021-33f9b867899d?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'was-im-expose-fehlt',
    title: 'Was im Exposé fehlt: 10 Angaben, die Käufer aktiv vom Verkäufer einfordern sollten',
    description: 'Sanierungshistorie, Heizungsalter, WEG-Protokolle, Baulasten, Schadenshistorie — 10 Pflichtangaben, die in Exposés meist fehlen und warum Sie sie aktiv anfragen sollten.',
    date: '11. April 2026',
    readTime: '12 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1560440021-33f9b867899d?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'exposes-richtig-lesen',
    title: 'Exposés richtig lesen für Einsteiger: 5 Schlüsselzahlen jedes Inserats',
    description: 'Quadratmeterpreis, Baujahr, Energieklasse, Hausgeld und Provision — die 5 wichtigsten Zahlen jedes Exposés und was Erstkäufer typischerweise unter- oder überschätzen.',
    date: '11. April 2026',
    readTime: '12 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'hauskauf-vorbereiten',
    title: 'Hauskauf vorbereiten: 60-Minuten-Check vor der ersten Besichtigung',
    description: 'Exposé auswerten, Lage recherchieren, Finanzierung überschlagen — die 60-Minuten-Vorprüfung, die teure Fehlbesichtigungen erspart und gute Angebote früh erkennt.',
    date: '11. April 2026',
    readTime: '11 Min',
    tags: ['Checkliste', 'Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'immobilien-vergleichen',
    title: 'Immobilien vergleichen: 8 Kennzahlen für einen aussagekräftigen Vergleich',
    description: 'Kaufpreis, €/m², Energieklasse, Hausgeld, Lage-Score — welche 8 Kennzahlen einen echten Immobilien-Vergleich ermöglichen und welche Vergleichsfehler Sie vermeiden.',
    date: '11. April 2026',
    readTime: '11 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1464082354059-27db6ce50048?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'sanierungsbedarf-erkennen',
    title: 'Sanierungsbedarf erkennen: Welche Hinweise schon im Exposé stehen',
    description: 'Baujahr, Energieklasse, fehlende Modernisierungs-Angaben — welche Exposé-Signale auf versteckten Sanierungsbedarf hindeuten und was eine Sanierung wirklich kostet.',
    date: '11. April 2026',
    readTime: '12 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'lagebewertung-hauskauf',
    title: 'Lagebewertung beim Hauskauf: 8 Faktoren über die Adresse hinaus prüfen',
    description: 'Makrolage, Mikrolage, Lärmkarten, Hochwasserrisiko, Bodenrichtwert — die 8 Lagefaktoren, die den Immobilienwert wirklich bestimmen, mit Prüf-Anleitung.',
    date: '11. April 2026',
    readTime: '11 Min',
    tags: ['Standort', 'Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1464082354059-27db6ce50048?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'kaufnebenkosten-immobilienkauf',
    title: 'Kaufnebenkosten Immobilienkauf: Grunderwerbsteuer, Notar, Makler & versteckte Kosten',
    description: 'Grunderwerbsteuer (3,5–6,5 %), Notar, Grundbuch, Makler — plus Sanierung, Umzug, Sonderumlagen. So berechnen Sie die wahren Gesamtkosten Ihres Immobilienkaufs.',
    date: '11. April 2026',
    readTime: '10 Min',
    tags: ['Finanzierung', 'Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'energieausweis-expose',
    title: 'Energieausweis im Immobilien-Exposé: Verbrauchs- vs. Bedarfsausweis erklärt',
    description: 'Verbrauchsausweis vs. Bedarfsausweis, Effizienzklassen A+ bis H, Heizkosten überschlagen — wie Sie Energiewerte im Exposé richtig einordnen und typische Mythen vermeiden.',
    date: '11. April 2026',
    readTime: '11 Min',
    tags: ['Energie', 'Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'warnsignale-expose',
    title: 'Warnsignale im Immobilien-Exposé: Welche Hinweise Käufer ernst nehmen müssen',
    description: 'Fehlende Pflichtdaten, Maklerfloskeln, unrealistische Preise — welche Warnsignale beim Hauskauf sofort misstrauisch machen und welche erst im Zusammenspiel kritisch werden.',
    date: '11. April 2026',
    readTime: '10 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1560440021-33f9b867899d?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'quadratmeterpreis-bewerten',
    title: 'Quadratmeterpreis bewerten: Wann ist eine Immobilie zu teuer?',
    description: 'Warum Vergleichswerte allein irreführend sein können und welche 7 Faktoren den fairen Quadratmeterpreis einer Immobilie wirklich bestimmen — mit Beispielen.',
    date: '11. April 2026',
    readTime: '9 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=450&fit=crop&auto=format&q=80',
  },
  {
    slug: 'expose-pruefen',
    title: 'Immobilien-Exposé prüfen: Warnsignale, Red Flags und versteckte Risiken vor der Besichtigung erkennen',
    description: 'Maklersprache decoded, typische Warnsignale beim Hauskauf, Red Flags im Exposé, fehlende Kennzahlen — systematisch Exposés auswerten und gezielt nachfragen, bevor Sie Zeit verlieren.',
    date: '11. April 2026',
    readTime: '10 Min',
    tags: ['Kaufratgeber'],
    image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&h=450&fit=crop&auto=format&q=80',
  },
]

// Map slug → lazy component (filled as posts are written)
export const POST_COMPONENTS: Record<string, React.LazyExoticComponent<React.ComponentType>> = {
  'grundsteuer-reform-2025-2026': lazy(() => import('./grundsteuer-reform-2025-2026')),
  'wohngebaeudeversicherung-hauskauf': lazy(() => import('./wohngebaeudeversicherung-hauskauf')),
  'geg-sanierungspflichten-altbau-kauf': lazy(() => import('./geg-sanierungspflichten-altbau-kauf')),
  'photovoltaik-immobilie-bewerten': lazy(() => import('./photovoltaik-immobilie-bewerten')),
  'risse-im-mauerwerk-beurteilen': lazy(() => import('./risse-im-mauerwerk-beurteilen')),
  'elektroinstallation-altbau-pruefen': lazy(() => import('./elektroinstallation-altbau-pruefen')),
  'haus-geerbt-verkaufen-vermieten': lazy(() => import('./haus-geerbt-verkaufen-vermieten')),
  'wohnrecht-niessbrauch-immobilie-kaufen': lazy(() => import('./wohnrecht-niessbrauch-immobilie-kaufen')),
  'bausparvertrag-immobilienkauf': lazy(() => import('./bausparvertrag-immobilienkauf')),
  'bausachverstaendiger-hauskauf-kosten': lazy(() => import('./bausachverstaendiger-hauskauf-kosten')),
  'uebergabeprotokoll-hauskauf': lazy(() => import('./uebergabeprotokoll-hauskauf')),
  'dach-pruefen-hauskauf': lazy(() => import('./dach-pruefen-hauskauf')),
  'asbest-im-haus-erkennen': lazy(() => import('./asbest-im-haus-erkennen')),
  'hochwasser-risiko-immobilie-pruefen': lazy(() => import('./hochwasser-risiko-immobilie-pruefen')),
  'neubau-bautraeger-vertrag-mabv': lazy(() => import('./neubau-bautraeger-vertrag-mabv')),
  'grundstueck-kaufen-worauf-achten': lazy(() => import('./grundstueck-kaufen-worauf-achten')),
  'zwangsversteigerung-immobilie-kaufen': lazy(() => import('./zwangsversteigerung-immobilie-kaufen')),
  'bodenrichtwert-verstehen-abfragen': lazy(() => import('./bodenrichtwert-verstehen-abfragen')),
  'notartermin-ablauf-hauskauf': lazy(() => import('./notartermin-ablauf-hauskauf')),
  'kaufvertrag-immobilie-pruefen': lazy(() => import('./kaufvertrag-immobilie-pruefen')),
  'erbbaurecht-erbpacht-kaufen': lazy(() => import('./erbbaurecht-erbpacht-kaufen')),
  'schimmel-feuchtigkeit-hauskauf': lazy(() => import('./schimmel-feuchtigkeit-hauskauf')),
  'heizungsarten-vergleich-kosten': lazy(() => import('./heizungsarten-vergleich-kosten')),
  'reservierungsgebuehr-immobilie': lazy(() => import('./reservierungsgebuehr-immobilie')),
  'vorfaelligkeitsentschaedigung': lazy(() => import('./vorfaelligkeitsentschaedigung')),
  'grundschuld-vs-hypothek': lazy(() => import('./grundschuld-vs-hypothek')),
  'kfw-wohneigentum-familien-2026': lazy(() => import('./kfw-wohneigentum-familien-2026')),
  'bonitaet-schufa-baufinanzierung': lazy(() => import('./bonitaet-schufa-baufinanzierung')),
  'erschliessungskosten-erschliessungsbeitrag': lazy(() => import('./erschliessungskosten-erschliessungsbeitrag')),
  'vorkaufsrecht-gemeinde-milieuschutz': lazy(() => import('./vorkaufsrecht-gemeinde-milieuschutz')),
  'baulasten-grunddienstbarkeiten': lazy(() => import('./baulasten-grunddienstbarkeiten')),
  'auflassungsvormerkung-erklaert': lazy(() => import('./auflassungsvormerkung-erklaert')),
  'wohnung-kaufen-vermieten-kapitalanlage': lazy(() => import('./wohnung-kaufen-vermieten-kapitalanlage')),
  'denkmalschutz-immobilie-kaufen': lazy(() => import('./denkmalschutz-immobilie-kaufen')),
  'hauskauf-ohne-eigenkapital': lazy(() => import('./hauskauf-ohne-eigenkapital')),
  'annuitaetendarlehen-erklaert': lazy(() => import('./annuitaetendarlehen-erklaert')),
  'sondertilgung-sinnvoll': lazy(() => import('./sondertilgung-sinnvoll')),
  'zinsbindung-10-oder-15-jahre': lazy(() => import('./zinsbindung-10-oder-15-jahre')),
  'anschlussfinanzierung-forward-darlehen': lazy(() => import('./anschlussfinanzierung-forward-darlehen')),
  'bieterverfahren-immobilie': lazy(() => import('./bieterverfahren-immobilie')),
  'provisionsfrei-immobilie-bedeutung': lazy(() => import('./provisionsfrei-immobilie-bedeutung')),
  'grundbuch-lesen': lazy(() => import('./grundbuch-lesen')),
  'teilungserklaerung-pruefen': lazy(() => import('./teilungserklaerung-pruefen')),
  'energetische-sanierung-foerderung-2026': lazy(() => import('./energetische-sanierung-foerderung-2026')),
  'grunderwerbsteuer-2026-bundeslaender': lazy(() => import('./grunderwerbsteuer-2026-bundeslaender')),
  'hauskauf-checkliste-2026': lazy(() => import('./hauskauf-checkliste-2026')),
  'kaufen-oder-mieten-2026': lazy(() => import('./kaufen-oder-mieten-2026')),
  'maklerprovision-immobilienkauf': lazy(() => import('./maklerprovision-immobilienkauf')),
  'notarkosten-grundbuchkosten-immobilienkauf': lazy(() => import('./notarkosten-grundbuchkosten-immobilienkauf')),
  'eigenkapital-immobilienkauf': lazy(() => import('./eigenkapital-immobilienkauf')),
  'kaufpreisfaktor-mietrendite': lazy(() => import('./kaufpreisfaktor-mietrendite')),
  'altbau-oder-neubau-kaufen': lazy(() => import('./altbau-oder-neubau-kaufen')),
  'expose-pruefen': lazy(() => import('./expose-pruefen')),
  'quadratmeterpreis-bewerten': lazy(() => import('./quadratmeterpreis-bewerten')),
  'warnsignale-expose': lazy(() => import('./warnsignale-expose')),
  'energieausweis-expose': lazy(() => import('./energieausweis-expose')),
  'kaufnebenkosten-immobilienkauf': lazy(() => import('./kaufnebenkosten-immobilienkauf')),
  'lagebewertung-hauskauf': lazy(() => import('./lagebewertung-hauskauf')),
  'sanierungsbedarf-erkennen': lazy(() => import('./sanierungsbedarf-erkennen')),
  'immobilien-vergleichen': lazy(() => import('./immobilien-vergleichen')),
  'hauskauf-vorbereiten': lazy(() => import('./hauskauf-vorbereiten')),
  'exposes-richtig-lesen': lazy(() => import('./exposes-richtig-lesen')),
  'was-im-expose-fehlt': lazy(() => import('./was-im-expose-fehlt')),
  'expose-analyse-vor-besichtigung': lazy(() => import('./expose-analyse-vor-besichtigung')),
  'angebotspreis-fair': lazy(() => import('./angebotspreis-fair')),
  'immobilienbewertung-kaeufer': lazy(() => import('./immobilienbewertung-kaeufer')),
  'hauskauf-mit-system': lazy(() => import('./hauskauf-mit-system')),
  'fehler-immobilienkauf': lazy(() => import('./fehler-immobilienkauf')),
  'immobilien-check-vor-kauf': lazy(() => import('./immobilien-check-vor-kauf')),
  'baujahr-einordnen': lazy(() => import('./baujahr-einordnen')),
  'zustand-folgekosten': lazy(() => import('./zustand-folgekosten')),
  'besichtigung-vorbereitung': lazy(() => import('./besichtigung-vorbereitung')),
  'expose-verstehen': lazy(() => import('./expose-verstehen')),
  'immobilien-realistischer-einordnen': lazy(() => import('./immobilien-realistischer-einordnen')),
  'daten-statt-bauchgefuehl': lazy(() => import('./daten-statt-bauchgefuehl')),
  'eigentumswohnung-kaufen-expose': lazy(() => import('./eigentumswohnung-kaufen-expose')),
  'einfamilienhaus-kaufen-expose': lazy(() => import('./einfamilienhaus-kaufen-expose')),
  'fehler-private-kaeufer': lazy(() => import('./fehler-private-kaeufer')),
  'zustand-richtig-einschaetzen': lazy(() => import('./zustand-richtig-einschaetzen')),
  'baujahr-und-modernisierung': lazy(() => import('./baujahr-und-modernisierung')),
  'grundriss-richtig-lesen': lazy(() => import('./grundriss-richtig-lesen')),
  'wohnflaeche-richtig-einordnen': lazy(() => import('./wohnflaeche-richtig-einordnen')),
  'hausgeld-ruecklagen-sonderumlage': lazy(() => import('./hausgeld-ruecklagen-sonderumlage')),
  'bilder-im-expose-bewerten': lazy(() => import('./bilder-im-expose-bewerten')),
  'nebenkosten-laufende-kosten': lazy(() => import('./nebenkosten-laufende-kosten')),
  'infrastruktur-pruefen': lazy(() => import('./infrastruktur-pruefen')),
  'immobilienkauf-mit-familie': lazy(() => import('./immobilienkauf-mit-familie')),
  'unterlagen-vor-immobilienkauf': lazy(() => import('./unterlagen-vor-immobilienkauf')),
  'immobilienanfragen-bearbeiten': lazy(() => import('./immobilienanfragen-bearbeiten')),
  'fristen-immobilienkauf': lazy(() => import('./fristen-immobilienkauf')),
  'rauchen-dampfen-wohnqualitaet': lazy(() => import('./rauchen-dampfen-wohnqualitaet')),
  'homeoffice-immobilienkauf': lazy(() => import('./homeoffice-immobilienkauf')),
  'wohnqualitaet-bewerten': lazy(() => import('./wohnqualitaet-bewerten')),
  'raeume-richtig-nutzen': lazy(() => import('./raeume-richtig-nutzen')),
  'fliesen-qualitaetsmerkmal-immobilie': lazy(() => import('./fliesen-qualitaetsmerkmal-immobilie')),
  'innenausbau-bewerten': lazy(() => import('./innenausbau-bewerten')),
}
