#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')
const POSTS_FILE = resolve(ROOT, 'src/components/blog/posts/index.ts')
const OUT = resolve(ROOT, 'public/sitemap.xml')
const BASE = 'https://immopruef.de'

const today = new Date().toISOString().slice(0, 10)

const src = readFileSync(POSTS_FILE, 'utf8')

// Extract slug + date + optionales updated aus jedem BlogMeta-Eintrag.
// Matches: slug: 'foo-bar', ... date: '11. April 2026', [updated: '13. Juli 2026',]
// `updated` muss unmittelbar auf `date` folgen (siehe BlogMeta in BlogLayout.tsx).
const entries = []
const re = /slug:\s*'([^']+)',[\s\S]*?date:\s*'([^']+)',(?:\s*updated:\s*'([^']+)',)?/g
for (const m of src.matchAll(re)) {
  entries.push({ slug: m[1], date: m[2], updated: m[3] })
}

function germanToIso(d) {
  const months = {
    januar: '01', februar: '02', märz: '03', april: '04', mai: '05', juni: '06',
    juli: '07', august: '08', september: '09', oktober: '10', november: '11', dezember: '12',
  }
  const m = d.match(/(\d{1,2})\.\s*([A-Za-zäöüÄÖÜß]+)\s*(\d{4})/)
  if (!m) return today
  const day = m[1].padStart(2, '0')
  const mon = months[m[2].toLowerCase()] || '01'
  return `${m[3]}-${mon}-${day}`
}

// lastmod = letzte inhaltliche Aenderung (updated), sonst Erstveroeffentlichung.
const blogUrls = entries
  .map(e => ({ loc: `${BASE}/blog/${e.slug}`, lastmod: germanToIso(e.updated || e.date), changefreq: 'monthly', priority: '0.7' }))

const staticUrls = [
  { loc: `${BASE}/`, lastmod: today, changefreq: 'weekly', priority: '1.0' },
  { loc: `${BASE}/expose-pruefen-lassen`, lastmod: today, changefreq: 'monthly', priority: '0.9' },
  { loc: `${BASE}/beispiel-analyse`, lastmod: today, changefreq: 'monthly', priority: '0.7' },
  { loc: `${BASE}/beispiel-premium-report`, lastmod: today, changefreq: 'monthly', priority: '0.7' },
  { loc: `${BASE}/blog`, lastmod: today, changefreq: 'weekly', priority: '0.8' },
  ...['finanzierung', 'checklisten', 'zustand', 'standort', 'energie', 'besichtigung']
    .map((s) => ({ loc: `${BASE}/blog/thema/${s}`, lastmod: today, changefreq: 'weekly', priority: '0.8' })),
  { loc: `${BASE}/rechner`, lastmod: today, changefreq: 'monthly', priority: '0.8' },
  { loc: `${BASE}/grunderwerbsteuer-rechner`, lastmod: today, changefreq: 'monthly', priority: '0.8' },
  { loc: `${BASE}/budgetrechner`, lastmod: today, changefreq: 'monthly', priority: '0.8' },
  { loc: `${BASE}/tilgungsrechner`, lastmod: today, changefreq: 'monthly', priority: '0.8' },
  { loc: `${BASE}/notarkosten-rechner`, lastmod: today, changefreq: 'monthly', priority: '0.8' },
  { loc: `${BASE}/mieten-oder-kaufen-rechner`, lastmod: today, changefreq: 'monthly', priority: '0.8' },
  { loc: `${BASE}/mietrendite-rechner`, lastmod: today, changefreq: 'monthly', priority: '0.8' },
  { loc: `${BASE}/instandhaltungsruecklage-rechner`, lastmod: today, changefreq: 'monthly', priority: '0.8' },
  { loc: `${BASE}/wohnflaechen-rechner`, lastmod: today, changefreq: 'monthly', priority: '0.8' },
  { loc: `${BASE}/kaufnebenkosten-index`, lastmod: today, changefreq: 'monthly', priority: '0.8' },
  ...[
    'baden-wuerttemberg', 'bayern', 'berlin', 'brandenburg', 'bremen', 'hamburg', 'hessen',
    'mecklenburg-vorpommern', 'niedersachsen', 'nordrhein-westfalen', 'rheinland-pfalz', 'saarland',
    'sachsen', 'sachsen-anhalt', 'schleswig-holstein', 'thueringen',
  ].map((s) => ({ loc: `${BASE}/kaufnebenkosten-${s}`, lastmod: today, changefreq: 'monthly', priority: '0.7' })),
  ...[
    'baden-wuerttemberg', 'bayern', 'berlin', 'brandenburg', 'bremen', 'hamburg', 'hessen',
    'mecklenburg-vorpommern', 'niedersachsen', 'nordrhein-westfalen', 'rheinland-pfalz', 'saarland',
    'sachsen', 'sachsen-anhalt', 'schleswig-holstein', 'thueringen',
  ].map((s) => ({ loc: `${BASE}/bodenrichtwert-${s}`, lastmod: today, changefreq: 'monthly', priority: '0.7' })),
  { loc: `${BASE}/ueber-uns`, lastmod: today, changefreq: 'yearly', priority: '0.5' },
]
const legalUrls = [
  { loc: `${BASE}/impressum`, lastmod: today, changefreq: 'yearly', priority: '0.2' },
  { loc: `${BASE}/datenschutz`, lastmod: today, changefreq: 'yearly', priority: '0.2' },
  { loc: `${BASE}/agb`, lastmod: today, changefreq: 'yearly', priority: '0.2' },
  { loc: `${BASE}/widerruf`, lastmod: today, changefreq: 'yearly', priority: '0.2' },
  { loc: `${BASE}/barrierefreiheit`, lastmod: today, changefreq: 'yearly', priority: '0.2' },
]

function urlBlock(u) {
  return `  <url>\n    <loc>${u.loc}</loc>\n    <lastmod>${u.lastmod}</lastmod>\n    <changefreq>${u.changefreq}</changefreq>\n    <priority>${u.priority}</priority>\n  </url>`
}

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <!-- Auto-generated by scripts/sitemap.mjs — manuelle Änderungen werden überschrieben -->

  <!-- Startseite & Blog-Index -->
${staticUrls.map(urlBlock).join('\n')}

  <!-- Blog Posts (${blogUrls.length}) -->
${blogUrls.map(urlBlock).join('\n')}

  <!-- Legal -->
${legalUrls.map(urlBlock).join('\n')}

</urlset>
`

writeFileSync(OUT, xml, 'utf8')
console.log(`sitemap.xml generiert: ${staticUrls.length + blogUrls.length + legalUrls.length} URLs (${blogUrls.length} Blog-Posts)`)
